baseURL = "/"
languageCode = "en-us"
title = "Hyperobjekt"
theme = "base-hugo-theme"
googleAnalytics = ""
paginate = 5
enableRobotsTXT = true

[imaging]
resampleFilter = "box"
quality = 70
anchor = "smart"

[params]
  # google_analytics_id=""
  hideFooter=false
  includeBootstrapJs=true
  containerMaxWidth=1200
  showActiveNav=true
  paginage=5

# main menu

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1



[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

# Assets needed
# -------------
# * Dark color menu button icon
