backend:
  name: git-gateway
  branch: analytics # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/uploads" # Media files will be stored in the repo under content/uploads (to make the image processing work we have to use this technique to spoof the images being page resources
public_folder: "/uploads" # The src attribute for uploaded media will begin with this

collections:
  #EL
  - label: "Eviction Lab"
    name: evictionlab
    preview_path: /el
    files:
        - label: EL monthly reports
          name: el_reports
          folder: "content/el"
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Date, name: date, widget: datetime}
            - {label: Childof, name: childof, widget: hidden, default: analytics}
            - {label: Layout, name: layout, widget: hidden, default: analytics-single}
            - {label: Embed code, name: body, widget: string}
            